language: php
php:
  - 7
  - nightly
#  - hhvm # PHP 7 syntax in Hack file only

before_install:
  - composer self-update

install:
  - composer install

script:
  - bin/phpspec run
  - bin/phpunit
  - bin/phpcs -p --standard=PSR2 --ignore=vendor,Spec.php .
