language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - bin/phpspec run
  - bin/phpcs -p --standard=PSR2 --ignore=vendor,Spec.php .

